---
title: "DataExercise3"
author: "Ash Munta"
date: "2024-11-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggdist)
```

```{r}
desc <- read_csv("data/desc_all.csv") 
e2_error <- read_csv("data/e2_error_df.csv")
e5_error <- read_csv("data/e5_error_df.csv")
e15_error <- read_csv("data/e15_error_df.csv")
```
```{r}
desc %>%
  distinct(Code, group_name)

```

```{r}
desc %>%
  ggplot(aes(y = no_categories)) +
  geom_histogram(binwidth = 1,
                 color = "white")
```

```{r}
desc %>%
  ggplot(aes(y=no_categories))+
  geom_histogram() +
  facet_grid(~group_name)
```

Noticed NA, lets make sure that is missing

```{r}
desc %>%
  distinct(group_name)
```
Also so noticed larger sample for some groups

```{r}
desc %>%
  count(group_name)
```

```{r}
averages <- desc %>%
  group_by(group_name) %>%
  summarise(
    avg_X = mean(X, na.rm = TRUE)
  )
averages
```
```{r}
grouped_cat_desc <- desc %>%
  group_by(group_name) %>%
  summarise(
    mean = mean(no_categories),
    sd = sd(no_categories)) %>%
  mutate(mean_sd = str_c(round(mean,2)," (", round(sd,2), ")"))
```

```{r}
desc %>% 
  filter(is.na(group_name) == FALSE) %>%
  mutate(full_group_name = case_when(group_name == "south_asian" ~ "South Asian",
                                     group_name == "se_asian" ~ "Southeast Asian",
                                     group_name == "non_asian_multi" ~ "Non-Asian Multilingual",
                                     group_name == "eng_mono" ~ "English monolingual diverse",
                                     group_name == "east_asian" ~ "East Asian",),
         full_group_name = factor(full_group_name,
                                  levels = c("English monolingual diverse",
                                             "Non-Asian Multilingual",
                                             "South Asian",
                                             "Southeast Asian",
                                             "East Asian"))) %>%
  ggplot(aes(y = full_group_name,
             x = no_categories,
             fill = full_group_name)) +
  geom_boxplot(color = "black",
               outliers = FALSE)+
    xlim(0,20) +
  labs(x = "Number of categories",
       y = "Group Name",
       title = "Avg Num of Categories per group") +
    theme_minimal() +
    theme(legend.position = "none") +
    scale_fill_viridis_d(option = "plasma") +
  annotate(geom = "text", x = 17.5, y = 1, label = filter(grouped_cat_desc, group_name =="east_asian")$mean_sd) +
  annotate(geom = "text", x = 17.5, y = 2, label = filter(grouped_cat_desc, group_name =="se_asian")$mean_sd) +
  annotate(geom = "text", x = 17.5, y = 3, label = filter(grouped_cat_desc, group_name =="south_asian")$mean_sd) +
  annotate(geom = "text", x = 17.5, y = 4, label = filter(grouped_cat_desc, group_name =="non-asian_multi")$mean_sd) +
  annotate(geom = "text", x = 17.5, y = 5, label = filter(grouped_cat_desc, group_name =="eng_mono")$mean_sd)

```


